### ISSUE TITLE
Hardcoded /lib

### ISSUE THREAD

**Issue by suve** [alemart/surgescript#3]
Hi, I'm a package maintainer in Fedora and I'm currently in the process of packaging OpenSurge (and thus, SurgeScript) for Fedora.

In Fedora, we stick with `/lib` on 32-bit architectures, but on 64-bit architectures, we use `/lib64`. This allows users to install both 64-bit and 32-bit versions of libraries, should they have a need to do so.

SurgeScript has `$PREFIX/lib` harcoded in three places:
- `CMakeLists.txt:142` - the dynamic library destination directory
- `CMakeLists.txt:151` - the static library destination directory
- `src/surgescript/misc/surgescript.pc.in:3` - the libdir as specified in the pkgconfig file

It would be nice if those places could be edited so they respect `-DLIB_INSTALL_DIR` or `-DLIB_SUFFIX`.

Sorry for not attaching a patch, but I have very little experience with CMake.

**Comment by alemart** [comment]
Hello, suve. Thank you for letting me know. I'll be adding a `LIB_SUFFIX` to CMake as soon as possible.

**Comment by alemart** [comment]
I have submitted an update. Please let me know if it works for you. I'll upload a new release with this patch soon after.

**Comment by suve** [comment]
I've just made test builds using the latest commit (255ba56d2042f476174165b714c31bedf2bcf540) and it works as expected, with `/lib` in the 32-bit build and `/lib64` in the 64-bit build.

**Comment by alemart** [comment]
Thank you. [SurgeScript v0.5.4.4](https://github.com/alemart/surgescript/tree/v0.5.4.4) includes this change and should be ready for packaging. There is an appdata.xml template in `src/surgescript/misc` which may bring you helpful information.

Since you're packaging Open Surge on Fedora as well, I suggest creating two separate packages: opensurge and surgescript (that's already the case on Debian). surgescript contains the runtime engine for this scripting language and does not depend on opensurge.

Let me know if you have any further questions.
